{% set name = "itertable" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/itertable-{{ version }}.tar.gz
  sha256: 0ebdd0919a71ac2b8850fc3f45990fbe9520ec3cfd65eba00ab8f92785459314

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - openpyxl
    - click

test:
  imports:
    - itertable
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Iterable API for tabular datasets including CSV, XLSX, XML, & JSON.
  home: https://github.com/wq/itertable/
  dev_url: https://github.com/wq/itertable/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
